export const TODO_ACTION_CONST = {
  CREATE_TODO: 'CREATE_TODO',
  CREATE_TODO_INPUT: 'CREATE_TODO_INPUT',
  UPDATE_TODO_INPUT: 'UPDATE_TODO_INPUT',
  CREATE_TODO_UPDATE: 'CREATE_TODO_UPDATE',
  CREATE_TODO_COMPLETE: 'CREATE_TODO_COMPLETE',
  CREATE_TODO_DELETE: 'CREATE_TODO_DELETE'
}